-- AGGREGATE FUNCTIONS --
COUNT(col) -- Returns the number of values. [Only one] -- No or NULL are counted.
MIN(col) -- Return the minimum value. [Only one] -- NULL are ignored.
MAX(col) -- Return the maximum value. [Only one] -- NULL are ignored.
AVG(int) -- Returns the average. [Only one] -- No or NULL values are ignored.
SUM(int) -- Returns the sumatory. [Only one]
SQRT(int) -- Returns the square root.
UPPER(str) -- Returns the upeercase version of the string.
LOWER(str) -- Returns the lowercase version of the string.
CONCAT(col1, col2) -- Returns a new column made of two more values, (cols or strings).
POWER (col , num) -- Return the column raised to the number.
