-- ORDER BY --
... ORDER BY columnName1 -- Will order by this column, alphabeticaly, or numercially depending the data type.
... ORDER BY columnName1, columnName2 -- If columnName1 items are the same, it sees de secondone (You can add more columns).
... ORDER BY 2, 3, 7 -- Instead of the column's name you can use it position.

-- SORT DIRECTION --
... ORDER BY columnName1 ASC -- The default.
... ORDER BY columnName1 DESC -- It order the items in descending order 
